version: '3'
services:
  dev:
    build: .
    links:
      - mysql
      - btcpayserver   
    ports:
      - 8080:80
    expose:
      - "80" 
    volumes:
      - "./html:/var/www/html"
    environment:
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  mysql:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    expose:
      - "3306"
    volumes:
      - "mariadb_datadir:/var/lib/mysql"

  btcpayserver:
    image: btcpayserver/btcpayserver:1.0.3.47
    expose:
      - "80"
    ports:
      - 8081:80
    environment:
      # BTCPay settings
      BTCPAY_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Database=btcpayserverregtest
      BTCPAY_NETWORK: regtest
      BTCPAY_CHAINS: "btc,ltc"
      BTCPAY_BTCEXPLORERURL: http://nbxplorer:32838/
      BTCPAY_LTCEXPLORERURL: http://nbxplorer:32838/
      BTCPAY_BIND: 0.0.0.0:80

      # NGINX settings
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: 49392
      
    links:
      - nbxplorer
      - postgres
    volumes:
      - "btcpay_datadir:/datadir"
      - "nbxplorer_datadir:/root/.nbxplorer"

  nbxplorer:
    image: nicolasdorier/nbxplorer:2.0.0.8
    restart: unless-stopped
    ports:
      - "32838:32838"
    expose: 
      - "32838"
    environment:
      NBXPLORER_NETWORK: regtest
      NBXPLORER_CHAINS: "btc,ltc"
      NBXPLORER_BTCRPCURL: http://bitcoind:43782/
      NBXPLORER_BTCNODEENDPOINT: bitcoind:39388
      NBXPLORER_BTCRPCUSER: ceiwHEbqWI83
      NBXPLORER_BTCRPCPASSWORD: DwubwWsoo3
      NBXPLORER_LTCRPCURL: http://litecoind:43782/
      NBXPLORER_LTCNODEENDPOINT: litecoind:39388
      NBXPLORER_LTCRPCUSER: ceiwHEbqWI83
      NBXPLORER_LTCRPCPASSWORD: DwubwWsoo3
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_VERBOSE: 1
      NBXPLORER_NOAUTH: 1
    links:
      - bitcoind
      - litecoind

  bitcoind:
    image: btcpayserver/bitcoin:0.17.0
    environment:
      BITCOIN_NETWORK: regtest
      BITCOIN_EXTRA_ARGS: |
        deprecatedrpc=signrawtransaction
        rpcuser=ceiwHEbqWI83
        rpcpassword=DwubwWsoo3
        rpcport=43782
        port=39388
        whitelist=0.0.0.0/0
        zmqpubrawblock=tcp://0.0.0.0:28332
        zmqpubrawtx=tcp://0.0.0.0:28333
    ports: 
      - "43782:43782"
      - "28332:28332"
    expose:
      - "43782" # RPC
      - "39388" # P2P
      - "28332" # ZMQ
      - "28333" # ZMQ
    volumes:
      - "bitcoin_datadir:/data"

  litecoind:
    container_name: woocommerce_litecoind
    image: nicolasdorier/docker-litecoin:0.16.3
    environment:
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        regtest=1
        port=39388
        rpcuser=ceiwHEbqWI83
        rpcpassword=DwubwWsoo3
        whitelist=0.0.0.0/0
    expose:
      - "43782"
      - "39388"
    volumes:
      - "litecoin_datadir:/data"

  postgres:
    image:  postgres:9.6.5
    volumes:
      - "postgres_datadir:/var/lib/postgresql/data"
  
volumes: 
  postgres_datadir:
  litecoin_datadir:
  bitcoin_datadir:
  nbxplorer_datadir:
  btcpay_datadir:
  mariadb_datadir: